trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: "UPDATE_TO_KUBERNETES_VERSION"
    value: "1.16.7"
  - name: "TEMP_FOLDER"
    value: ".tmp/"
  - name: "CLUSTERS_FILE_NAME"
    value: "clusterUpgradeCandidatesSummary.json"
  - name: "ERR_LOG_FILE_NAME"
    value: "err.log"
  - name: "EXCLUDED_CLUSTERS_LIST"
    value: "clusterRG-1:clusterName-1 clusterRG-2:clusterName-2 clusterRG-N:clusterName-N"

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'GBB Subscription(40545cc3-81f4-42c9-953d-67534438918e)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Load Main/Bootstrap Script
      source main.sh
      
      # Run main function
      main